{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"test_results\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "d57c36a7-bb24-4b35-866f-0af021b32ac7",
        "fromColumn": "requested_datetime",
        "fromTable": "test_results",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_443b88de-6ff9-4b7b-96be-d1ce9b1bfde4"
      },
      {
        "name": "ed596e69-d2f7-42dc-a991-1616996af2aa",
        "fromColumn": "updated_datetime",
        "fromTable": "test_results",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_28967888-5f06-4cc5-a427-73da7f8308d7"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "test_results",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "service_request_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "490bd3ac-45c9-4f3c-bbff-3d6bde175c6e",
            "sourceColumn": "service_request_id",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1218b3cd-be80-4ef6-8a42-0d486f23c9e7",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "status_notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fb01ca1-40dc-49db-99f4-94181871b896",
            "sourceColumn": "status_notes",
            "summarizeBy": "none"
          },
          {
            "name": "service_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08a765de-309b-43f5-8cc4-258f319ca3cd",
            "sourceColumn": "service_name",
            "summarizeBy": "none"
          },
          {
            "name": "service_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af8f66e1-77b2-4226-8153-9f6098acf56a",
            "sourceColumn": "service_code",
            "summarizeBy": "none"
          },
          {
            "name": "requested_datetime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "14fa5d3f-0a61-4e9b-ac7e-f2319a4d0d60",
            "sourceColumn": "requested_datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_443b88de-6ff9-4b7b-96be-d1ce9b1bfde4"
                },
                "isDefault": true,
                "relationship": "d57c36a7-bb24-4b35-866f-0af021b32ac7"
              }
            ]
          },
          {
            "name": "updated_datetime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1cb271c2-9099-41a9-97b4-bb19c3b521d1",
            "sourceColumn": "updated_datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_28967888-5f06-4cc5-a427-73da7f8308d7"
                },
                "isDefault": true,
                "relationship": "ed596e69-d2f7-42dc-a991-1616996af2aa"
              }
            ]
          },
          {
            "name": "address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33396897-9346-4aa7-a270-0d859839b0f0",
            "sourceColumn": "address",
            "summarizeBy": "none"
          },
          {
            "name": "lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "932f1bfb-6fa1-426e-a9b3-eec3db75ca36",
            "sourceColumn": "lat",
            "summarizeBy": "sum"
          },
          {
            "name": "long",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ba3f013a-fc61-4943-a010-6121083b4a1f",
            "sourceColumn": "long",
            "summarizeBy": "sum"
          },
          {
            "name": "token",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13128d05-75c5-43e4-afa8-ef1a981263bb",
            "sourceColumn": "token",
            "summarizeBy": "none"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3a2767d-5c23-4338-b9db-e1dbcf57ad79",
            "sourceColumn": "description",
            "summarizeBy": "none"
          },
          {
            "name": "service_type_output",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b2a0e19-ea24-4890-9c62-4b6061de71cb",
            "sourceColumn": "service_type_output",
            "summarizeBy": "none"
          },
          {
            "name": "is_emergency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "409fcd9f-f042-4080-84be-d72af988c2d6",
            "sourceColumn": "is_emergency",
            "summarizeBy": "none"
          },
          {
            "name": "recommendations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f88188e-c827-4aaa-a7b5-6d0349722a1e",
            "sourceColumn": "recommendations",
            "summarizeBy": "none"
          },
          {
            "name": "summary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e8ca60e-a35f-4e56-9eeb-8b4fa9234d8b",
            "sourceColumn": "summary",
            "summarizeBy": "none"
          },
          {
            "name": "rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60e2abae-16d2-4d7c-b3fe-01d20652e480",
            "sourceColumn": "rating",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f58f3cd9-144e-4ce0-9b2f-eb4c33d8dd50",
        "measures": [
          {
            "name": "Is Emergency",
            "expression": "IF(FIRSTNONBLANK(test_results[is_emergency],1=1)=TRUE(), TRUE(), FALSE())",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c0f961ae-d37a-4d68-9cbf-c384d4e53f2a"
          }
        ],
        "partitions": [
          {
            "name": "test_results",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\cnone\\Documents\\github\\atx-311-llm-data-augmentation\\llm\\test_results.csv\"),[Delimiter=\",\", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"service_request_id\", type text}, {\"status\", type text}, {\"status_notes\", type text}, {\"service_name\", type text}, {\"service_code\", type text}, {\"requested_datetime\", type datetime}, {\"updated_datetime\", type datetime}, {\"address\", type text}, {\"lat\", type number}, {\"long\", type number}, {\"token\", type text}, {\"description\", type text}, {\"service_type_output\", type text}, {\"is_emergency\", type logical}, {\"recommendations\", type text}, {\"summary\", type text}, {\"rating\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_76419010-a3d3-4ee8-a84c-c224e01528b6",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3fe717b9-1571-453e-ba4d-46a797c25c9d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "39518288-228f-4ef0-a331-b089e41d100b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1a7ab0d2-c7dc-4d5d-b38a-3c81e6043dc7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "965ce85a-0e4d-48bf-b068-e02731c1bfb5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8132af57-398d-4354-8d68-cab98996ad21",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2264ebc1-fc05-439c-80cc-11283291816f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bd481792-5ea5-4a81-9d64-6ae11c28d7a8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3439c10c-c6e5-49ab-9ed1-d3ab6d84aa4d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7de6c9ef-c7e3-4e95-a22b-a67ab4537be8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4ca666b0-3aba-4c8a-b854-24b5b92e7e27",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7b0b118d-7829-4dc6-b9e1-3ccbf55fddc9",
                "ordinal": 3
              }
            ],
            "lineageTag": "c11a4f74-c9a6-47d6-8e44-5dc7d6c6dbe2"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b191ce09-75a4-46bc-8b69-f70950fcdbce",
        "partitions": [
          {
            "name": "DateTableTemplate_76419010-a3d3-4ee8-a84c-c224e01528b6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_443b88de-6ff9-4b7b-96be-d1ce9b1bfde4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "604ee591-b77d-4080-a776-f60d91a5dbdd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "26d3d3a4-232e-4b78-bf66-5066c3a3fab2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f7e5bf85-39f0-490f-a1b5-732e82f1b934",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cd1779e5-d47d-4df1-8f92-1430f5650660",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f9aa4e2c-4d07-4604-b3ca-a6df9f3f46e8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "01a09547-d7cc-4c51-8538-d0625ccb8d10",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0ada2e80-a624-4d9f-8c9e-ef9b7096f8bd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3d0ea479-4802-4530-bfc7-a9dde8cfaf82",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b5790b5f-a2d8-4c55-9437-4339968eca90",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "12809c2f-7c9e-4804-886a-8c04982b5442",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "791c01ed-4184-4602-a212-5a1732b6afef",
                "ordinal": 3
              }
            ],
            "lineageTag": "ca115197-4183-4747-9c8d-da6eb41354be"
          }
        ],
        "isHidden": true,
        "lineageTag": "8a42d820-3fdb-4fd0-8239-4131bcace4bc",
        "partitions": [
          {
            "name": "LocalDateTable_443b88de-6ff9-4b7b-96be-d1ce9b1bfde4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('test_results'[requested_datetime])), 1, 1), Date(Year(MAX('test_results'[requested_datetime])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_28967888-5f06-4cc5-a427-73da7f8308d7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "86fcd922-0678-4aa9-b337-76915d317029",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4a4cc052-b078-4d2f-8f89-db06add321de",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6e4e9aef-7b10-4d69-ae70-5299441b02bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9445e0f9-589b-42a4-84e5-e2ffe21ad23c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24188905-42fd-40c0-a9e7-cbe595c31b12",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3365cd15-cbb5-4835-b6fb-0ebfeae514a8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4d2ffe2a-8228-4fe2-bfd9-66cfecdf95d4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4e2c74bf-8517-4923-9fb3-c3110be03783",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "97017175-8a9b-4679-ab62-3178641eeaab",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "631a1062-ac1a-41e4-aedf-7c46706aebd1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "86d54841-8e74-4c5b-b12a-dede0c210d4d",
                "ordinal": 3
              }
            ],
            "lineageTag": "6b8f8c15-4761-4a42-96af-492f5fcd1069"
          }
        ],
        "isHidden": true,
        "lineageTag": "b00e46e6-1601-4978-a7b9-b6dbaffee24a",
        "partitions": [
          {
            "name": "LocalDateTable_28967888-5f06-4cc5-a427-73da7f8308d7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('test_results'[updated_datetime])), 1, 1), Date(Year(MAX('test_results'[updated_datetime])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}